### PR TITLE
Add support for Monash recordings

### PR DESCRIPTION
**Pull request by mcpower**
…as well as some minor fixes. Running a local copy confirms that it's working as intended, including pages with multiple pages of results.

May as well change the name and icon of the extension if you're merging this.

This shouldn't have changed anything with the UniMelb support, but please double check this.

### CODE REVIEW

**Comment by yxliang01** [comment]
@mcpower thank you for your contribution :+1: . responses for the commits:
3544ccd: It's already supported in version 1.0.8 which is the currently available version in Chrome store
befc138: thanks for fixing that!
2fef0db: Thanks for that. Have you tried to download the monash recordings?

I will merge your pull requests tomorrow alongside with a few new features. :laughing:

**Comment by mcpower** [comment]
If you are planning on merging #2, don't merge this one and fix up the tab query in your own commit. #2 should be a superset of this PR: I'll confirm whether it works with Monash tomorrow.

**Comment by yxliang01** [comment]
@mcpower had you tried to download the Monash recordings?

**Comment by yxliang01** [comment]
I had done merging the pulls. @mcpower Please inform me when you had tried downloading the Monash Recordings. Thank You

**Comment by yxliang01** [comment]
Tested by my friend, Monash recordings are supported.

**Pull request closed without merging**
